import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navebar from "@/app/layout/Navebar";
import ToastProvider from "@/lib/ToastProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dk Store",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <ToastProvider/>
          <Navebar/>
          <div className="w-full container mx-auto my-10">{children}</div>
        </ClerkProvider>
        </body>
    </html>
  );
}
