import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navebar from "@/components/Navebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dk Store",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <Navebar/>
        {children}
        </ClerkProvider>
        </body>
    </html>
  );
}
